### ISSUE TITLE
Suggestions...

### ISSUE THREAD

**Issue by rushprint** [asim/emque#2]
Hi Asim.

I just came by this project searching a simple, easy to use, docker swarm friendly message queue solution.
Many other popular message queues are not suitable for my current job.

I am very impressed for your design. It's what I am looking for.

However, after short review I am not sure but concluded it is long way to go.
If you don't mind I want to share my requirements.

1. Java script client including auto reconnection support.
2. Message requeue support from client.
3. Message persistent for HA; seems now just write only and have no saving path config.
4. Message TTL support (Auto remove on timeout)

Best regards.
Sungkyu Kim.

**Comment by asim** [comment]
I do not have any bandwidth to do these things, please feel free to PR. Thanks for the suggestions.

**Comment by rushprint** [comment]
Thank you for your response.
Unfortunately I don't have either, but someday If I can I will.
