### ISSUE TITLE
Divide and Conquer -  PUSH/PULL

### ISSUE THREAD

**Issue by WillianBR** [asim/emque#4]
I have download your code and test it with for a while. It work just fine by the instructions.

But I'm wondering if the unique pattern it's implements is the **PUB/SUB**.

May be a **PUSH/PULL** pattern ([Push/Pull Pattern](https://zguide.zeromq.org/docs/chapter1/#Divide-and-Conquer)).  One of those scenario when one or more process are pushing data to the queueue, but each message it's supposed to be handled by one and only one worker.

**_I have worked with PUSH/PULL on ZeroMQ and it work just fine._**

`A  push  pull  messaging  pattern  is  defined  as  a  messaging pattern  when  devices  push  data  to  the  server  and  others  canpull data from the server. Unlike the publish subscribe systemwhere  all  devices  that  are  subscribed  to  a  topic  get  the  datawhereas in push/pull devices need to pull the data explicitly.`

**Comment by asim** [comment]
It depends on the way it's configured. You can opt into sending to one or all. So yea given its a set of proxies it might seem more like push pull. This was a quick hack so I'm not really spending time thinking about it or the semantics.

**Comment by WillianBR** [comment]
> It depends on the way it's configured. You can opt into sending to one or all. So yea given its a set of proxies it might seem more like push pull. This was a quick hack so I'm not really spending time thinking about it or the semantics.

Do you mean if I use a set of proxies , it will do a round robin message distribution?

Because as I said, each message must be handled by only worker only!  

In the scenario each message is a task to be execute and the output sent forward!

**Comment by asim** [comment]
See the readme and the binary flags. There's clustering and sharing. Clustering will send the same message to all. Sharding will only send to 1.
